# Generated by Django 5.2.4 on 2025-07-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
